"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
IS_TESTING = "test" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="")
if not SECRET_KEY and IS_TESTING:
    SECRET_KEY = "test-secret-key"

# GraphQL UI (GraphiQL) toggle for local development
GRAPHQL_GRAPHIQL = config("GRAPHQL_GRAPHIQL", default=DEBUG, cast=bool)

# JWT settings for GraphQL auth
JWT_SECRET = config("JWT_SECRET", default=SECRET_KEY)
JWT_ALGORITHM = config("JWT_ALGORITHM", default="HS256")
JWT_ACCESS_TTL_MINUTES = config("JWT_ACCESS_TTL_MINUTES", default=15, cast=int)
JWT_REFRESH_TTL_DAYS = config("JWT_REFRESH_TTL_DAYS", default=7, cast=int)

ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="127.0.0.1,localhost,testserver,arnova-207y.onrender.com",
    cast=lambda v: [s.strip() for s in v.split(",")],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_extensions",
    "shop",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "shop.middleware.account_lockout.AccountLockoutMiddleware",
    "shop.middleware.ip_access_control.IPAccessControlMiddleware",
    "shop.middleware.admin_security.AdminSecurityMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "shop.middleware.security_headers.SecurityHeadersMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

primary_db_url = config(
    "POSTGRES_URL",
    default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
)
if not primary_db_url:
    primary_db_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=primary_db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

# Validate POSTGRES_URL format
db_url = primary_db_url
if db_url.startswith("http://") or db_url.startswith("https://"):
    # Invalid URL format - use SQLite as fallback
    import sys

    print(
        "WARNING: POSTGRES_URL has invalid format (http/https). Using SQLite.",
        file=sys.stderr,
    )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
elif "neon.tech" in db_url and "sslmode=require" not in db_url:
    import sys

    print(
        "WARNING: POSTGRES_URL missing sslmode=require. "
        "Neon requires SSL; ensure your URL includes '?sslmode=require'.",
        file=sys.stderr,
    )

# Add SSL certificate for Supabase (PostgreSQL only)
if config("SSL_SUPABASE", default=None):
    db_engine = DATABASES["default"].get("ENGINE", "")
    if "postgresql" in db_engine or "postgres" in db_engine:
        ssl_cert_path = BASE_DIR / config("SSL_SUPABASE")
        if ssl_cert_path.exists():
            if "OPTIONS" not in DATABASES["default"]:
                DATABASES["default"]["OPTIONS"] = {}
            DATABASES["default"]["OPTIONS"].update(
                {
                    "sslmode": "require",
                    "sslrootcert": str(ssl_cert_path),
                }
            )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    path
    for path in [
        BASE_DIR / ".next" / "static",
        BASE_DIR / "public",
    ]
    if path.exists()
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Performance optimizations
USE_ETAGS = True
USE_GZIP = True

# Redis Cache Configuration
REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PARSER_CLASS": "redis.connection.HiredisParser",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "KEY_PREFIX": "arnova",
        "TIMEOUT": 300,
    }
}

# Session backend using Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Database connection pooling
if not IS_TESTING:
    DATABASES["default"]["CONN_MAX_AGE"] = 600
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    # Only add statement_timeout for non-pooled connections
    if "pooler" not in primary_db_url:
        DATABASES["default"]["OPTIONS"] = DATABASES["default"].get("OPTIONS", {})
        DATABASES["default"]["OPTIONS"].update(
            {
                "connect_timeout": 10,
                "options": "-c statement_timeout=30000",
            }
        )

# Session security
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access for frontend
SESSION_COOKIE_SAMESITE = "None"  # Required for cross-origin requests
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Allow persistent sessions
SESSION_COOKIE_AGE = 2592000  # 30 days for remember me
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_DOMAIN = None  # Allow cross-subdomain

# HTTPS Security Headers
if not DEBUG and not IS_TESTING:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
else:
    # Development: disable HTTPS redirects
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

# Cache settings for static files
if not DEBUG:
    STATICFILES_STORAGE = (
        "django.contrib.staticfiles.storage." "ManifestStaticFilesStorage"
    )

# CSRF Configuration for Unified Frontend-Backend
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)
CSRF_COOKIE_SAMESITE = "None"  # Required for cross-origin requests
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 86400
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        "http://127.0.0.1:8000,https://127.0.0.1:8443,"
        "http://localhost:8000,https://localhost:8443,"
        "https://arnova-207y.onrender.com"
    ),
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CSRF_FAILURE_VIEW = "django.views.csrf.csrf_failure"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# M-Pesa Daraja API Configuration
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_ENVIRONMENT = os.getenv("MPESA_ENVIRONMENT", "sandbox")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE", "174379")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Login URLs
LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/admin/"

# Admin IP Whitelist (production only)
ADMIN_ALLOWED_IPS = config(
    "ADMIN_ALLOWED_IPS",
    default="127.0.0.1,::1,localhost",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "shop": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# CORS Configuration for Vercel Frontend
CORS_ALLOWED_ORIGINS = [
    "https://arnova-207y.onrender.com",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://localhost:8443",
    "https://127.0.0.1:8443",
]

# Allow all Vercel domains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
