# Generated by Django 6.0.1 on 2026-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
