# Generated by Django 6.0.1 on 2026-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
    ]
